/**
 * 前端（app/page.tsx）文案的语言层。
 * 中文版：t() 原样返回传入的中文字符串、模板函数复现原来的模板——输出与引入语言开关前逐字相同。
 * 英文版：按中文原文查表；模板函数给英文模板。
 */
import { IS_EN } from "./locale";

const en: Record<string, string> = {
  "故事角色": "Story character",
  "角色资料将在故事中逐步公开。": "Character details unlock as the story goes on.",
  "角色资料尚未公开。": "Character details are not public yet.",
  "编译结果缺少 locked opening，未进入群聊。请点击重聊重新编译。": "The compiled result has no locked opening, so the chat did not start. Click Start Over to recompile.",
  "本章线索": "This chapter's clue",
  "论文正文待录入。": "Paper text not yet entered.",
  "进入": "Enter",
  "先确认退路": "Check the way out first",
  "影像证物": "Visual evidence",
  "音频记录": "Audio record",
  "监控影像": "Surveillance footage",
  "文件证物": "Document evidence",
  "消息记录": "Message log",
  "获得线索": "Clue acquired",
  "线索图片待添加": "Clue image pending",
  "影像待解锁": "Image locked",
  "线索音频待添加": "Clue audio pending",
  "视频待添加": "Video pending",
  "一条新消息已收入案件档案。": "A new message has been filed in the case archive.",
  "打开": "Open",
  "编译响应缺少 sessionId": "Compile response is missing sessionId",
  "编译响应缺少剧情会话令牌": "Compile response is missing the story session token",
  "上一页档案": "Previous archive page",
  "下一页档案": "Next archive page",
  "玛雅留下的未经剪辑 Vlog": "Maya's unedited vlog",
  "查看影像": "Watch the footage",
  "正在创建新的独立会话……": "Creating a new independent session…",
  "新的会话已经就绪。先从这段 Vlog 开始。": "New session ready. Start with the vlog.",
  "Prompt 1/2 编译失败": "Prompt 1/2 compile failed",
  "剧情影像": "Story image",
  "本次身份": "Your identity",
  "你": "You",
  "本轮响应缺少剧情会话令牌": "This turn's response is missing the story session token",
  "本轮生成失败，请重试。故事状态没有在页面中继续推进。": "This turn failed. Try again; the story has not advanced on the page.",
  "终局投票失败": "Final vote failed",
  "终局响应不完整": "Ending response incomplete",
  "可选": "optional",
  "输入你想扮演的角色": "Enter who you want to play",
  "例如：聪明但嘴硬的天才实习生": "e.g. a brilliant intern who never admits being wrong",
  "确认": "Confirm",
  "案件档案 / 03:00": "Case file / 03:00",
  "章节": "Chapters",
  "由故事状态解锁": "Unlocked by story progress",
  "↺ 从头开始": "↺ Start over",
  "静默纽约": "The Silent New York",
  "角色正在载入…": "Loading characters…",
  "章节影像": "Chapter visual",
  "视频待缓存": "Video not cached",
  "正在播放": "Playing",
  "最后一帧已锁定为背景": "Last frame locked as background",
  "玛雅的 Vlog": "Maya's vlog",
  "关闭 Vlog": "Close vlog",
  "当前现场": "Current scene",
  "你加入故事的方式": "How you joined the story",
  "你的判断": "Your call",
  "播放旧音响里的童年旋律": "Play the childhood melody from the old speaker",
  "断续、失真，像一张转坏的旧唱片": "Broken up and distorted, like a warped old record",
  "先播放完玛雅的 Vlog，看看在场的人各自看见了什么。": "Watch Maya's vlog first, and see what each person in the room saw.",
  "Vlog 已播放，正在等待 Prompt 1/2 返回锁定开场……": "Vlog finished. Waiting for Prompt 1/2 to return the locked opening…",
  "未知错误": "unknown error",
  "正在装载锁定开场……": "Loading the locked opening…",
  "本轮没有通过协议": "This turn failed the protocol",
  "知道了": "Got it",
  "正在让在场的人认识你……": "Letting the people in the room get to know you…",
  "本章最后的画面还停在这里……": "The chapter's last frame is still holding here…",
  "正在生成一整段电影探索场景……": "Generating a full cinematic scene…",
  "输入你的行动或判断": "Type your action or your read on the scene",
  "说说你的判断，或者直接问一个人…": "Say what you make of it, or ask someone directly…",
  "发送": "Send",
  "掷骰子，随机说一句协议提供的话": "Roll the dice: say a random line the protocol provides",
  "🎲 随机回答": "🎲 Random line",
  "剧情转盘：点击展开，上下拖动并松手直接发送": "Story dial: tap to expand, drag up or down and release to send",
  "选择": "Choose",
  "关闭角色卡": "Close character card",
  "这一章留下的东西，已经收入你的案件档案。": "What this chapter left behind is now in your case file.",
  "章节声音": "Chapter audio",
  "章节过场": "Chapter transition",
  "可播放": "Ready",
  "等待素材": "Awaiting media",
  "章节媒体预览": "Chapter media preview",
  "点击下方按钮播放": "Press the button below to play",
  "素材待添加": "Media pending",
  "播放童年音乐": "Play the childhood song",
  "播放章节媒体": "Play chapter media",
  "收下线索": "Take the clue",
  "章节入口": "Chapter entrance",
  "摧毁梦境": "Destroy the dream",
  "保留梦境": "Keep the dream",
  "最后一票属于你": "The last vote is yours",
  "结局影像": "Ending footage",
  "结局视频待添加": "Ending video pending",
  "从头开始": "Start over",
  "文风": "Style",
  "选择文风，只影响之后的轮次": "Choose a writing style; it only affects the turns after this one",
};

/** 中文原文 → 当前语言。中文版恒等；英文版查表（漏译时回落到中文，构建脚本会检查漏译）。 */
export function t(zh: string): string {
  return IS_EN ? (en[zh] ?? zh) : zh;
}

function chineseChapter(number: number) {
  return ["零", "一", "二", "三", "四", "五", "六", "七", "八", "九", "十"][number] ?? String(number);
}

export const ui = {
  /** `第 3 章` */
  chapterN: (n: number) => IS_EN ? `Chapter ${n}` : `第 ${n} 章`,
  /** `第 3 章 · 标题`（顶栏） */
  chapterHeading: (n: number, title: string) => IS_EN ? `Chapter ${n} · ${title}` : `第 ${n} 章 · ${title}`,
  /** `第三章 · 完成` */
  chapterComplete: (n: number) => IS_EN ? `Chapter ${n} · Complete` : `第${chineseChapter(n)}章 · 完成`,
  /** `进入第三章` */
  enterChapter: (n: number) => IS_EN ? `Enter Chapter ${n}` : `进入第${chineseChapter(n)}章`,
  /** `第三章 · CHAPTER ENTRY` */
  chapterEntryEyebrow: (n: number) => IS_EN ? `Chapter ${n} · CHAPTER ENTRY` : `第${chineseChapter(n)}章 · CHAPTER ENTRY`,
  transitionTitle: (title: string) => IS_EN ? `${title} · Chapter transition` : `${title} · 章节过场`,
  compileFailedHttp: (status: number) => IS_EN ? `Prompt 1/2 compile failed (HTTP ${status})` : `Prompt 1/2 编译失败（HTTP ${status}）`,
  compileFailedWith: (error: string) => IS_EN ? `Prompt 1/2 compile failed: ${error}` : `Prompt 1/2 编译失败：${error}`,
  turnFailedHttp: (status: number) => IS_EN ? `This turn failed (HTTP ${status})` : `本轮生成失败（HTTP ${status}）`,
  eventCountMismatch: (got: number, min: number, max: number) => IS_EN ? `Protocol check failed: received ${got} events, expected ${min}–${max}.` : `协议校验失败：本轮收到 ${got} 条事件，要求 ${min}–${max} 条。`,
  choiceCountMismatch: (got: number, want: number) => IS_EN ? `Protocol check failed: received ${got} choices, expected ${want}.` : `协议校验失败：本轮收到 ${got} 个选项，要求 ${want} 个。`,
  enteredChapter: (n: number, title: string) => IS_EN ? `Now in Chapter ${n}: ${title}.` : `已进入第 ${n} 章：${title}。`,
  chapterDone: (n: number) => IS_EN ? `Chapter ${n} complete.` : `第 ${n} 章已完成。`,
  identityJoinInput: (profile: string) => IS_EN ? `I join the scene as "${profile}".` : `我以“${profile}”的身份加入现场。`,
  identityJoinDisplay: (profile: string) => IS_EN ? `You join the scene as "${profile}".` : `你以“${profile}”的身份加入现场。`,
  enterWithCostume: (label: string, n: number, title: string) => IS_EN ? `You go with "${label}" and enter Chapter ${n}: ${title}.` : `你们换上${label}，进入第 ${n} 章：${title}。`,
  enterCautious: (n: number, title: string) => IS_EN ? `You check the way out and the time behind the door, then enter Chapter ${n} together: ${title}.` : `你们先确认门后的退路和时间，再一起进入第 ${n} 章：${title}。`,
  enterBold: (n: number, title: string) => IS_EN ? `You step through the door. Now in Chapter ${n}: ${title}.` : `你选择跨过那扇门。已进入第 ${n} 章：${title}。`,
  viewCard: (name: string) => IS_EN ? `View ${name}'s character card` : `查看${name}角色卡`,
  characterCard: (name: string) => IS_EN ? `${name}'s character card` : `${name}角色卡`,
};
