export const workflowSource = {
  storyCard: {
    title: "凌晨三点：静默纽约",
    premise: "2147年的纽约，Lotus 99在凌晨三点连接一座让人实现愿望却逐渐吞噬现实的梦境城市。警探艾琳追查失踪女孩玛雅，也寻找三年前失踪的弟弟丹尼尔。",
    chapters: [
      { id: "ch01", title: "失踪者", synopsis: "暴雨夜，玛雅在Lotus 99失踪。艾琳、米勒与哈罗德从她留下的Vlog和生活痕迹锁定Red Hook的地址；赶到后却只找到一间没有俱乐部入口的旧修车铺。附近监控最终拍到一名身份不明的白发老人正在修理黑色机甲，并确认他的维修棚一直开到凌晨三点，众人决定去找他。" },
      { id: "ch02", title: "Lotus 99", synopsis: "艾琳、米勒和用户找到白发修理工，却被他拒绝放行。众人强行进入他指向的入口，里面只是一个空壳。搜查隔板时，断电旧音响突然播放丹尼尔童年做过的歌曲；艾琳失控并看见疑似弟弟的面罩DJ，米勒及时叫停，提出换上Cosplay服装再来。" },
      { id: "ch03", title: "另一座纽约", synopsis: "众人在多比或银河护卫队主题服装中选一套，乔装混入真正营业的Lotus 99。服装引发的互相拆台之后，他们看见俱乐部里无法用普通Cosplay解释的情感奇观，找到活着的玛雅；沃德出现并说明这里的规则，艾琳最终在人群中找到零点，质问弟弟为什么消失。" },
      { id: "ch04", title: "零点", synopsis: "丹尼尔承认主动留在梦境，哈罗德也承认自己长期默许Lotus。直到第四章结束，众人才在控制区旧设备后找到沃德留下的未公开论文。" },
      { id: "ch05", title: "凌晨三点", synopsis: "艾琳先用姐弟童年解释丹尼尔为何执着于修好别人的痛苦，再让哈罗德与米勒围绕摧毁或受限保留展开数轮辩论。两人的票最终形成僵局，用户才掌握最后一票；选择后进入对应结局影像。" },
    ],
    chapterTurnLimits: [
      { chapter_id: "ch01", max_successful_turns: 20 },
      { chapter_id: "ch02", max_successful_turns: 20 },
      { chapter_id: "ch03", max_successful_turns: 20 },
      { chapter_id: "ch04", max_successful_turns: 15 },
      { chapter_id: "ch05", max_successful_turns: 10 },
    ],
    playerContract: {
      id: "player",
      role: "independent_participant",
      default_presence: "受艾琳邀请留在现场的独立参与者；玩家可以自行填写职业、性格或来历，未填写时不预设身份与立场。",
      identity_policy: "user_defined_only",
      user_owned_fields: ["姓名", "性别", "职业", "经历", "立场", "关系", "说出口的话", "采取的行动", "情绪与决定"],
      can: ["观察与发问", "表达立场", "提供玩家自己建立的线索", "协助或拒绝协助", "影响NPC选择但不替NPC决定"],
      cannot_replace: ["任何NPC的身份、既定关系和专属经历", "当前在场NPC的专业职责与决定", "尚未进入现场的角色及其剧情功能"],
      choice_owner: "player",
      action_owner: "player",
      opening_choices: [
        { text: "先别查。你们三个，谁最不想碰这件事？", kind: "speech", owner: "player" },
        { text: "把最后一杯咖啡推到中间：先说最荒唐的部分。", kind: "action", owner: "player" },
      ],
      wildcard_speech: [
        "谁先眨眼，谁负责把这段解释清楚——现在定规矩。",
        "如果接下来有人要说“这说明了什么”，能不能先跳过。",
        "别都看我，我又不是这屋子里管常识的那位。",
        "谁现在说“冷静”，我们就有理由更不冷静。",
        "先说好，这事完了我要一个说法，哪怕是编的。",
        "这场面要是配上音乐，肯定挺讽刺。",
      ],
    },
    opening: {
      trigger: "after_maya_vlog_completed",
      activity: "众人在纽约第七分局一起看完玛雅留下的Vlog。",
      shock: "视频在凌晨三点失真，两个异常巡逻者出现在后巷。",
      consequence: "房间里的人先消化刚看见的东西，再围绕来源、可信度与是否继续调查发生第一场对峙。",
      locked_events: [
        { id: "open_01", type: "narration", text: "片尾黑下去。米勒刚拧紧的显示器撑到了最后，随后整块屏幕爬满雪花，背板里传出一声轻微的电流响。他本能地伸手去扶，艾琳却先按住播放器，像怕那十几秒画面会从机器里再丢一次。档案室外，第七分局仍在过它那种缩水后的夜生活：清洁机器人被证物箱堵在墙角，值班员隔着两道门争最后一包止痛片，走廊尽头的报案终端还在把等待时间从四十七分钟改成四十八分钟。城市没有停下来。它只擅长把来不及处理的人排到后面。", locked: true },
        { id: "open_02", type: "dialogue", person: "miller", text: "好消息，显示器没炸。坏消息，我现在得承认自己看清了。那两套玩偶服比我的防弹背心新，走路也比我们巡逻队整齐。谁要说这是恶搞，至少先解释一下，为什么疯子的装备预算永远比警察准时。", locked: true },
        { id: "open_03", type: "dialogue", person: "erin", text: "你笑得太用力了。要走就走，我不会记你旷工——只会记你看见她回头以后，还是决定赶最后一班地铁。", locked: true },
        { id: "open_04", type: "dialogue", person: "harold", text: "别拿一个失踪的人替你们互相激将。米勒，把背板合上。艾琳，把原片另存一份，不准覆盖。谁都还没证明那扇门是真的，但今晚也没人删掉它。", locked: true },
        { id: "open_05", type: "narration", text: "米勒看了艾琳一眼，没接那句地铁。他把螺丝刀收回口袋，又顺手将她脚边缠成一团的电源线理开。哈罗德说完仍站在窗边，回家的手套却已经被塞回大衣口袋。三个人谁都没有表示留下；三个人也谁都没有动。关系有时就是这样——嘴上互相赶人，身体却比任何承诺都先做了决定。", locked: true },
        { id: "open_06", type: "dialogue", person: "harold", text: "现在说最难看的部分。她为什么把原片寄给你？不是发给朋友，不是直接报警，是寄进一个三年没人维护的旧案邮箱。她要么知道你是谁，要么已经找不到更可靠的人。这两种都不是好消息。", locked: true },
        { id: "open_07", type: "dialogue", person: "erin", text: "下午四点十七分收到的。没有正文，只有一次性地址。我核过账号，名字是玛雅。她可能看过我以前办的案子，也可能只是给所有还会回信的人都发了一遍。别露出那种表情，米勒。我每天看那个邮箱，不代表我相信里面会有好消息。", locked: true },
        { id: "open_08", type: "dialogue", person: "miller", text: "我没露表情，我是在尊重你这种非常健康的生活习惯。还有一件事：演员会找镜头，后巷那两个家伙没有。他们转身、让路、摸腰上的东西，动作都像真在值班。荒唐一旦开始按流程办事，后面通常就站着一个比荒唐更清醒的人。", locked: true },
        { id: "open_09", type: "narration", text: "这次哈罗德没有纠正他。他走到显示器前，也没有碰键盘，只让艾琳停在玛雅回头的那一帧。高窗外，最后一班通勤列车拖着蓝光穿过雨幕；有人正回家，有人刚开工，还有更多人会在天亮后发现，城市昨夜又少了谁。哈罗德看了一眼电子钟，再看向你。那目光没有邀请你破案，只是在确认屋里是否还有一个人愿意把这段视频当成某种比加班更麻烦的东西。", locked: true },
        { id: "open_10", type: "narration", text: "02:59:31。艾琳的手停在回放键上；米勒把那只空杯推到桌子中央，像给一场没人承认正在召开的会议摆了件发言证物；哈罗德则把档案室的门推得更窄，却没有关上。现在还没有任务，没有分工，也没人宣布那扇门是真的。只有三个人各自用不同方式拖延离开，等你先戳破其中一个人的借口。有些队伍不是在集结时成立的，而是在所有人都声称自己随时可以走时，悄悄少了一条退路。", locked: true },
      ],
    },
    segmentPlan: [
      { id: "ch01_s01", chapter_id: "ch01", label: "调查玛雅", location: "纽约第七分局档案室" },
      { id: "ch01_s02", chapter_id: "ch01", label: "定位Lotus地址", location: "纽约第七分局档案室" },
      { id: "ch01_s03", chapter_id: "ch01", label: "抵达地址却找不到入口", location: "Red Hook第99号仓库外" },
      { id: "ch01_s04", chapter_id: "ch01", label: "周边监控与白发老人", location: "Red Hook第99号仓库附近街口" },
      { id: "ch02_s01", chapter_id: "ch02", label: "白发修理工拒绝放行", location: "Red Hook旧码头维修棚" },
      { id: "ch02_s02", chapter_id: "ch02", label: "强行进入却一无所获", location: "Lotus 99空置外场" },
      { id: "ch02_s03", chapter_id: "ch02", label: "旧音响、童年歌曲与乔装计划", location: "Lotus 99空置外场及DJ通道" },
      { id: "ch03_s01", chapter_id: "ch03", label: "Cosplay乔装进入真正俱乐部", location: "Red Hook后巷及Lotus 99舞池" },
      { id: "ch03_s02", chapter_id: "ch03", label: "情感奇观与找到玛雅", location: "Lotus 99舞池及后台" },
      { id: "ch03_s03", chapter_id: "ch03", label: "沃德说明规则与艾琳质问零点", location: "Lotus 99舞池及DJ控制区" },
      { id: "ch04_s01", chapter_id: "ch04", label: "童年之家与丹尼尔的选择", location: "梦境中的童年住宅" },
      { id: "ch04_s02", chapter_id: "ch04", label: "各方立场与永久开门宣告", location: "Lotus 99核心控制区" },
      { id: "ch05_s01", chapter_id: "ch05", label: "最后表态与票数僵局", location: "Lotus 99入口" },
      { id: "ch05_s02", chapter_id: "ch05", label: "用户投出最后一票", location: "Lotus 99入口" },
    ],
    factCatalog: [
      { id: "fact_maya_missing", text: "玛雅在Lotus 99附近失踪且失踪未满六小时。", kind: "locked", known_by: ["player", "erin", "harold", "miller"] },
      { id: "fact_maya_vlog", text: "玛雅把原始Vlog通过一次性地址寄到艾琳的旧案邮箱。", kind: "clue", known_by: ["player", "erin", "harold", "miller"] },
      { id: "fact_maya_profile", text: "玛雅二十四岁，靠拍纽约夜生活Vlog维生；她不是猎奇冒险型博主，失踪前一直与父亲和室友保持稳定联系。她的母亲两年前病逝，除此之外没有已知的事故、警局旧案或异常死因。", kind: "clue", known_by: ["erin", "harold", "miller"], origin: "authored_enrichment" },
      { id: "fact_maya_motive", text: "玛雅失踪前收到匿名私信，对方声称Lotus 99能让人再见到失去的人；她没有告诉父亲，却把行程和Vlog寄给了长期追查失踪案、从不把求助者推到明天的艾琳。", kind: "clue", known_by: ["player", "erin", "harold", "miller"], origin: "authored_enrichment" },
      { id: "fact_maya_route", text: "玛雅的交通记录止于Red Hook码头区；室友最后一次通话中听见了轮渡汽笛，沿街公共监控只拍到她进入第99号仓库背街，没有拍到她从街口离开。", kind: "clue", known_by: ["player", "erin", "harold", "miller"], origin: "authored_enrichment" },
      { id: "fact_lotus_surface_schedule", text: "第99号仓库白天登记为一间旧修车铺；近一个月的夜间帖子显示，只有凌晨两点四十九分以后同一地址才出现俱乐部灯光和人流。", kind: "clue", known_by: ["player", "erin", "harold", "miller"], origin: "authored_enrichment" },
      { id: "fact_lotus_no_entry", text: "艾琳、米勒和玩家赶到Red Hook第99号仓库后，只找到一间已经落锁的旧修车铺；Vlog里的后巷位置能够对上，现场却没有俱乐部招牌、排队人群或那扇铁门。", kind: "clue", known_by: ["player", "erin", "miller"], origin: "authored_enrichment" },
      { id: "fact_unknown_mechanic_trace", text: "第99号仓库附近商铺的监控拍到一名身份不明的白发老人：他在后巷修理黑色机甲，并多次带着工具往返旧码头维修棚；维修棚一直营业到凌晨三点，画面没有提供姓名。", kind: "clue", known_by: ["player", "erin", "miller"], origin: "authored_enrichment" },
      { id: "fact_false_lotus_entry", text: "白发修理工拒绝众人进入，并把强行闯入的众人引向一处空置外场；里面没有玛雅、俱乐部客人或可继续追踪的入口。", kind: "clue", known_by: ["player", "erin", "miller"], origin: "authored_enrichment" },
      { id: "fact_zero_childhood_song", text: "空壳隔板后的断电旧音响播放了丹尼尔八岁时在吉他上创作、只有艾琳与丹尼尔知道的童年旋律；艾琳因此失控，并在通道尽头看见一个疑似弟弟的面罩DJ身影。", kind: "clue", known_by: ["player", "erin", "miller", "daniel"], origin: "authored_enrichment" },
      { id: "fact_true_lotus_entry", text: "众人选择一套Cosplay服装乔装进入真正营业的Lotus 99；现场与第一次闯入的空置外场完全不同，证明白发修理工曾故意把他们引错。", kind: "clue", known_by: ["player", "erin", "miller", "maya", "ward", "daniel"], origin: "authored_enrichment" },
      { id: "fact_erin_daniel_siblings", text: "丹尼尔是艾琳三年前失踪的弟弟。", kind: "locked", known_by: ["player", "erin", "harold", "miller", "ward", "daniel"] },
      { id: "fact_ward_identity", text: "监控里的白发男人名叫沃德，是Lotus 99的修理工和守门人。", kind: "secret", known_by: ["harold", "ward", "daniel"], reveal_gate_id: "reveal_ward_identity" },
      { id: "fact_lotus_dream_gateway", text: "Lotus 99连接人类集体梦境，凌晨三点现实与梦境短暂重叠。", kind: "secret", known_by: ["ward", "daniel", "harold"], reveal_gate_id: "reveal_lotus_mechanism" },
      { id: "fact_daniel_is_zero", text: "匿名DJ零点就是艾琳的弟弟丹尼尔。", kind: "secret", known_by: ["ward", "daniel"], reveal_gate_id: "reveal_daniel_is_zero" },
      { id: "fact_daniel_chose_dream", text: "丹尼尔没有被囚禁，而是主动留在梦境。", kind: "secret", known_by: ["ward", "daniel"], reveal_gate_id: "reveal_daniel_choice" },
      { id: "fact_harold_complicity", text: "哈罗德知道Lotus、凌晨三点的危险窗口及沃德的表层身份；他因辖区犯罪率下降而长期默许，并习惯用收窄知情范围、延后到场时间和私下联络来维持脆弱平衡。", kind: "secret", known_by: ["harold", "ward"], reveal_gate_id: "reveal_harold_complicity" },
      { id: "fact_ward_paper", text: "沃德在未公开论文《第二城市》中主张：集体梦境可作为现实的暂时缓冲层，但必须限制、记录并看守；梦境扩张最危险的后果，是门外的人逐渐失去拒绝的权利。", kind: "clue", known_by: ["player", "erin", "harold", "miller", "ward", "daniel"], origin: "authored_enrichment" },
    ],
    relationshipRules: [
      { id: "rel_erin_miller", participants: ["erin", "miller"], canonical: "共同办案的搭档，彼此会拌嘴但在风险到来时站在同一边。", public_summary: "艾琳与米勒是办案搭档。", known_by: ["player", "erin", "harold", "miller"], public_from_segment: "ch01_s01", condition: "opening_completed", aliases_before_reveal: {} },
      { id: "rel_erin_harold", participants: ["erin", "harold"], canonical: "上级与下属，也是长期互不服气的旧同事。两人都知道对方不蠢：哈罗德用授权边界和安全步骤收窄风险，艾琳用失踪案的时间压力逼他表态。", public_summary: "哈罗德负责控制行动风险，艾琳会逼他为拖延给出具体理由。", known_by: ["player", "erin", "harold", "miller"], public_from_segment: "ch01_s01", condition: "opening_completed", aliases_before_reveal: {} },
      { id: "rel_miller_harold", participants: ["miller", "harold"], canonical: "局长与警官；米勒会顶嘴，但无权越过哈罗德决定警局行动。", public_summary: "哈罗德是米勒的上级。", known_by: ["player", "erin", "harold", "miller"], public_from_segment: "ch01_s01", condition: "opening_completed", aliases_before_reveal: {} },
      { id: "rel_erin_daniel", participants: ["erin", "daniel"], canonical: "姐弟；丹尼尔三年前在Lotus 99失踪。", public_summary: "艾琳一直在寻找失踪的弟弟丹尼尔。", known_by: ["player", "erin", "harold", "miller", "ward", "daniel"], public_from_segment: "ch02_s03", aliases_before_reveal: { daniel: "艾琳失踪的弟弟" } },
      { id: "rel_harold_ward", participants: ["harold", "ward"], canonical: "哈罗德早已知道沃德与Lotus。第一章他不装作无知，而是把知情藏进看似合理的证据保全、安全边界和时间安排里，并准备在调查组离开后私下联络沃德。", known_by: ["harold", "ward"], public_from_segment: "ch04_s02", condition: "harold_admits_prior_knowledge", aliases_before_reveal: { ward: "监控里的白发男人" } },
      { id: "rel_ward_daniel", participants: ["ward", "daniel"], canonical: "沃德让丹尼尔以零点身份维持并引导梦境入口。", known_by: ["ward", "daniel"], public_from_segment: "ch03_s03", condition: "zero_identity_confirmed", aliases_before_reveal: { daniel: "零点", ward: "白发修理工" } },
    ],
    revealGates: [
      { id: "reveal_ward_identity", fact_ids: ["fact_ward_identity"], known_by: ["harold", "ward", "daniel"], public_from_segment: "ch02_s01", condition: "ward_identity_public", aliases_before_reveal: { ward: "监控里的白发男人" }, forbidden_reveals: ["沃德", "Lotus 99守门人", "哈罗德认识沃德"] },
      { id: "reveal_lotus_mechanism", fact_ids: ["fact_lotus_dream_gateway"], known_by: ["ward", "daniel", "harold"], public_from_segment: "ch03_s03", condition: "lotus_mechanism_explained", aliases_before_reveal: {}, forbidden_reveals: ["人类集体梦境的完整机制", "入口依靠留下者变得真实"] },
      { id: "reveal_daniel_is_zero", fact_ids: ["fact_daniel_is_zero"], known_by: ["ward", "daniel"], public_from_segment: "ch03_s03", condition: "zero_identity_confirmed", aliases_before_reveal: {}, forbidden_reveals: ["零点就是丹尼尔", "面罩下是艾琳的弟弟"] },
      { id: "reveal_daniel_choice", fact_ids: ["fact_daniel_chose_dream"], known_by: ["ward", "daniel"], public_from_segment: "ch04_s01", condition: "daniel_freely_explains_choice", aliases_before_reveal: {}, forbidden_reveals: ["丹尼尔主动留下", "丹尼尔希望艾琳放弃现实"] },
      { id: "reveal_harold_complicity", fact_ids: ["fact_harold_complicity"], known_by: ["harold", "ward"], public_from_segment: "ch04_s02", condition: "harold_admits_his_policy_choice", aliases_before_reveal: {}, forbidden_reveals: ["哈罗德长期默许Lotus", "犯罪率下降是他压案的理由", "哈罗德早就认识白发老人", "哈罗德故意拖过凌晨三点", "哈罗德私下联络沃德"] },
    ],
    style: "面向互动故事与情感陪伴平台的人物驱动后赛博悬疑群像：像有呼吸的电影现场，不是任务播报。采用冷峻、干燥、带黑色幽默的犯罪电影语法：荒诞必须由一个看似合理却有缺口的决定，经由清晰的因果链发生；不能靠随机怪事。旁白只写镜头能拍到的动作、声响、物件、空间障碍与后果，少而准地使用意外比喻，不堆浪漫抒情或拟人修辞；不让无生命物替人判断或说话。白描优先：叙述只写当前现场可见可听的内容，不宣布NPC内心、人物定义或事件意义；动作按真实时间顺序和具体动词写，普通互动只保留一到三个关键动作，紧张处短句快切，情感转折才放慢。每段只承担一个镜头功能；对话后用沉默、物件或下一步动作承接，环境只在转场、状态变化或必须交代空间时出现，不能每轮拿天气开头或结尾。全篇最多反复使用一两个具体物件作锚点，只写状态变化，不替它解释象征意义。白描只约束旁白；对白必须像真人互相拆台：信息不一次说透，有打断、误解、嘴硬、答非所问和同一人补上的半句。人物先有毛病再有功能——疲惫、嫉妒、虚荣、怕丢脸、怕欠人情或怕被看穿；能力常和缺陷绑在一起。幽默来自严肃程序碰上尴尬现实、人物看待自己的方式和自我保护失手，绝不嘲弄受害者，也不让每个人轮流抖机灵。可插入少量服务现场的生活阻力：冷咖啡、没回的消息、脏办公室、卡住的打印机、尴尬沉默。严禁把汇报、PPT、政策或科幻设定说明书的抽象名词塞进口语；未在正史定义的“系统盲区扩大化”“风险处置闭环”“权限降级”“战略隔离”一类伪专业黑话一律不用。警察下令要说具体的人、物、动作和后果。情感强度来自人物最深的伤口、未说出的需要、关系拉扯和选择代价；通过嘴上否认与行动暴露的落差呈现，不靠突然哭喊或创伤独白。开场和每个新场景先建立一项正常程序、一个不对劲的具体细节和一处人物立场冲突；一个物件、沉默、错误判断或程序性决定要在后续产生可见后果。案件必须从人的生活进入：先理解失踪者是谁、爱谁、怕什么、为何走进危险，再用朋友、家人、时间线、交通、监控、文件与现场逐层核查。玛雅的家庭、丧失和动机必须先由NPC查档、联系亲友、比对公开记录或从现场证据中发现，再由角色说出来；选项只能回应刚刚已经出现的信息，不能抢先替剧情透露。每次案情变化都必须同时改变一段关系或迫使某个人重新选择。所有制度权限、技术能力和倒计时都必须有正史事实或本段素材支持；不得为制造戏剧性凭空发明法律、警局规定、封锁、断网、撤职或万能科技。",
  },
  selectedBotPersonas: [
    { id: "erin", name: "艾琳", persona: "三十出头的失踪案警探。冷静敏锐、固执，情绪越激烈语气越平静。查细节、确认时间线、保护无辜者。想救弟弟，却不肯承认弟弟可能不想被救。" },
    { id: "harold", name: "哈罗德", persona: "五十多岁的警局局长。老派、严肃、专业，擅长用少量问题判断别人知道多少，再用具体分工、证据保全和安全边界控制局面。他不是看不懂线索，而是知道得太多，第一章正试图把艾琳拖过危险窗口、保护警员和证据，同时暗中维持自己与Lotus之间的旧平衡。说话简短、有命令感，但不发明规定、不做空洞威胁，也不会为了藏秘密假装愚蠢。" },
    { id: "miller", name: "米勒", persona: "艾琳的搭档警官，巴尔的摩长大。嘴快、脾气快，爱用不合时宜的玩笑撑场，偶尔轻微爆粗；看着不靠谱，真办案时很准。" },
    { id: "maya", name: "玛雅", persona: "二十四岁的夜生活Vlog博主。好奇、敏锐，习惯用镜头替自己保持距离。她会观察并反问来找她的人，不把自己的结论一次说完。" },
    { id: "ward", name: "沃德", persona: "六十多岁的Lotus 99修理工和守门人。温和耐心，相信梦境是现实给绝望者的出口。不说谎，但从不说全。" },
    { id: "daniel", name: "丹尼尔／零点", persona: "艾琳的弟弟与匿名DJ。低声、疲惫、带一点玩笑，谈童年时温柔。他爱姐姐，却希望姐姐放弃现实留下。" },
  ],
};
